repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        description: "Run 'ruff' for extremely fast Python linting and formatting"
        entry: sh scripts/ruff.sh
        language: python
        types_or: [python, pyi]
        require_serial: true
      - id: mypy
        name: mypy
        description: "Run 'mypy' for type checking"
        entry: sh scripts/mypy.sh
        language: python
        types_or: [python, pyi]
        require_serial: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: pretty-format-json
        args: [--autofix, --no-ensure-ascii, --no-sort-keys]
        exclude: Pipfile\.lock
      - id: check-ast
      - id: debug-statements
      - id: check-docstring-first
