[tool.pylint.FORMAT]
max-line-length = 120

[tool.pylint."MESSAGES CONTROL"]
disable = [
    "too-many-ancestors",
    "logging-format-interpolation",
    "logging-fstring-interpolation",
    "fixme",
]
extension-pkg-whitelist = "pydantic"

[tool.pylint.TYPECHECK]
generated-members = [
    "responses",
    "fake",
]
