# NOTE: you have to use single-quoted strings in TOML for regular expressions.
# It's the equivalent of r-strings in Python.  Multiline strings are treated as
# verbose regular expressions by Black.  Use [ ] to denote a significant space
# character.

[tool.black]
line-length = 120
target-version = ["py39"]
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 120

[tool.pylint.FORMAT]
max-line-length = 120

[tool.pylint."MESSAGES CONTROL"]
disable = [
    "too-many-ancestors",
    "logging-format-interpolation",
    "logging-fstring-interpolation",
    "fixme",
]
extension-pkg-whitelist = "pydantic"

[tool.pylint.TYPECHECK]
generated-members = [
    "responses",
    "fake",
]

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
python_files = [
    "tests.py",
    "test_*.py",
    "*_tests.py",
]

markers = [
]

addopts = [
    "--cov-report",
    "term-missing:skip-covered",
]

env = [
    "ENV=TEST",
]

[tool.coverage.run]
omit = [
]