name: Code quality

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv==v2022.3.28
        export PIPENV_VENV_IN_PROJECT=1
        pipenv install --dev
    - name: Analysing the code with pylint
      run: |
        .venv/bin/pylint $(git ls-files '*.py')
    - name: Black formatter
      run: |
        .venv/bin/black --check  .
    - name: Test with pytest
      run: |
        .venv/bin/pytest
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - name: Mypy type checker
      run: |
        .venv/bin/mypy .
    - name: Isort import sorter
      run: |
        .venv/bin/isort . --check --diff
